export const challenges = {
	nf10kOneStepP1: {
		challengeName: "Neura Funded 10k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 10000,
		challengePrice: 109,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000001",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf10kOneStepF: {
		challengeName: "Neura Funded 10k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 10000,
		challengePrice: 109,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000001",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf25kOneStepP1: {
		challengeName: "Neura Funded 25k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 25000,
		challengePrice: 265,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000002",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf25kOneStepF: {
		challengeName: "Neura Funded 25k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 25000,
		challengePrice: 265,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000002",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf50kOneStepP1: {
		challengeName: "Neura Funded 50k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 50000,
		challengePrice: 359,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000003",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf50kOneStepF: {
		challengeName: "Neura Funded 50k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 50000,
		challengePrice: 359,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000003",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf100kOneStepP1: {
		challengeName: "Neura Funded 100k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 100000,
		challengePrice: 549,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000004",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf100kOneStepF: {
		challengeName: "Neura Funded 100k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 100000,
		challengePrice: 549,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000004",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf200kOneStepP1: {
		challengeName: "Neura Funded 200k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 200000,
		challengePrice: 969,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000005",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf200kOneStepF: {
		challengeName: "Neura Funded 200k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 200000,
		challengePrice: 969,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000005",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf300kOneStepP1: {
		challengeName: "Neura Funded 300k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 300000,
		challengePrice: 1345,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000006",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf300kOneStepF: {
		challengeName: "Neura Funded 300k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 300000,
		challengePrice: 1345,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000006",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf400kOneStepP1: {
		challengeName: "Neura Funded 400k oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 400000,
		challengePrice: 1600,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000007",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf400kOneStepF: {
		challengeName: "Neura Funded 400k oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 400000,
		challengePrice: 1600,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000007",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf1mOneStepP1: {
		challengeName: "Neura Funded 1M oneStep",
		challengeType: "oneStep",
		currentPhase: "phase1",
		accountSize: 1000000,
		challengePrice: 3699,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000009",
		challengeStages: {
			phase1: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "360 Days",
				profitTarget: 7,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: false,
				leverage: 100,
				stage: "phase1",
			},
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf1mOneStepF: {
		challengeName: "Neura Funded 1M oneStep",
		challengeType: "oneStep",
		currentPhase: "funded",
		accountSize: 1000000,
		challengePrice: 3699,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000009",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 4,
				maxDrawdown: 8,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 100,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf5kInstantF: {
		challengeName: "Neura Funded 5k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 5000,
		challengePrice: 230,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000008",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 3,
				maxDrawdown: 6,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 50,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf10kInstantF: {
		challengeName: "Neura Funded 10k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 10000,
		challengePrice: 380,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000009",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 3,
				maxDrawdown: 6,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 50,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf25kInstantF: {
		challengeName: "Neura Funded 25k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 25000,
		challengePrice: 769,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000010",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 3,
				maxDrawdown: 6,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 50,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf50kInstantF: {
		challengeName: "Neura Funded 50k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 50000,
		challengePrice: 1209,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000011",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 3,
				maxDrawdown: 6,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 50,
				stage: "funded",
			},
		},
		__v: 0,
	},
	nf100kInstantF: {
		challengeName: "Neura Funded 100k Instant Funding",
		challengeType: "funded",
		currentPhase: "funded",
		accountSize: 100000,
		challengePrice: 2419,
		platform: "Mt5",
		broker: "Neura",
		status: "active",
		challengeId: "NF-000012",
		challengeStages: {
			phase1: null,
			phase2: null,
			funded: {
				maxDailyDrawdown: 3,
				maxDrawdown: 6,
				tradingPeriod: "Unlimited",
				profitTarget: null,
				minTradingDays: 2,
				drawdownType: "equity-based",
				profitSpilt: "90/10",
				payouts: true,
				leverage: 50,
				stage: "funded",
			},
		},
		__v: 0,
	},
};
